services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "3000"
    ports:
      - "80:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - WDS_SOCKET_PORT=0
      - TSC_COMPILE_ON_ERROR=true
      - ESLINT_NO_DEV_ERRORS=true
      - REACT_APP_WS_HOST=wss.trdoan20.tech
    depends_on:
      - backend
    networks:
      - traffic-network

  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - ./server:/app
    environment:
      - CORS_ORIGINS=http://localhost,https://trdoan20.tech,https://www.trdoan20.tech,https://api.trdoan20.tech
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    networks:
      - traffic-network

  nginx:
    image: nginx:latest
    ports:
     - "80:80"
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
     - frontend
     - backend
    networks:
     - traffic-network

networks:
  traffic-network:
    driver: bridge
