# backend/config.yaml (Dashcam Simple Version)

# --- Input Source ---
# 0, 1, ... cho webcam/dashcam kết nối USB, hoặc đường dẫn tới file video test
# video_source: 0
video_source: "/home/trdoan/workspace/traffic-app/Snaptik.app_7262913210154487048.mp4"

# --- Model & Inference ---
model_path: "./models/best.onnx" # Đảm bảo đúng đường dẫn
device: "cpu" # "cuda" hoặc "cpu"
inference:
  confidence_threshold: 0.5 # Có thể cần tăng ngưỡng tin cậy cho biển báo

# --- Class Names ---
# QUAN TRỌNG: Để code tự đọc từ model nếu có (xóa hoặc comment phần này)
# Nếu model không có sẵn tên class, bạn PHẢI định nghĩa chúng ở đây khớp với ID 0-6
class_names:
  0: "Cấm ngược chiều"
  1: "Cấm dừng và đỗ"
  2: "Cấm rẽ"
  3: "Giới hạn tốc độ"
  4: "Cấm còn lại"
  5: "Nguy hiểm"
  6: "Hiệu lệnh"
#   # ... (nếu model của bạn có các class khác)

# --- Warning Configuration ---
# Danh sách các Class ID của biển báo sẽ kích hoạt cảnh báo khi được phát hiện bởi dashcam
# Bạn cần quyết định biển nào thực sự cần cảnh báo cho người lái khi thấy nó
# Ví dụ: Cảnh báo khi thấy biển Nguy hiểm, Cấm ngược chiều, Cấm rẽ, Giới hạn tốc độ?
# Cân nhắc: Biển Cấm dừng/đỗ có cần cảnh báo ngay khi thấy không, hay chỉ cần hiển thị?
warning_trigger_sign_ids: [0, 2, 3, 5] # Ví dụ: Cấm ngược chiều, Cấm rẽ, Tốc độ, Nguy hiểm

# --- Output ---
output:
  sound_alert_path: "sounds/alert.mp3" # Đường dẫn file âm thanh
  # Không cần draw_zones cho dashcam ở kịch bản này